baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-initio'
paginate = 10

[params]
    name = "DasAng"
    description = "❝Sometimes you need to let go to gain something better❞"
    avatarclass = "circle"
    author = "DasAng"
    DateForm = "January 2, 2006"
    year = 2024

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = false
    showFooterFollowMe = false
    showFooterTextWidget = false
    showFooterFormWidget = false

    [[menu.main]]
    name = "home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 5
